### PR TITLE
fix: IsRepoInitialized recursive check and handle empty index

### LINKED ISSUE #98: feat: Repository Root Discovery in Subdirectories
**Objective**
`IsRepoInitialized()` only checks for `.kitkat` in the current working directory preventing commands from running inside subfolders

**How to Reproduce**

1. Initialize a repository at the project root
2. Create a subdirectory and enter it (`mkdir sub && cd sub`)
3. Run `kitkat status`
4. The command fails claiming it is not a kitkat repository

**Implementation Steps**

1. Locate `IsRepoInitialized` in `internal/core/helpers.go`
2. Refactor the logic to use a loop that checks the current directory for `.kitkat`
3. If not found, move to the parent directory and check again until the system root is reached
4. Update path resolution logic to ensure `RepoDir` constants point to the discovered root path

**Files to Modify**

* `internal/core/helpers.go`

### PR DESCRIPTION
**Pull request by roshankumar0036singh**
# Fix: IsRepoInitialized Recursive Check & Empty Index Handling

## Description
This PR addresses two issues related to repository initialization and command execution from subdirectories.
fixes #98 

1.  **`IsRepoInitialized` Check**:
    - Previously, `IsRepoInitialized` only checked for the existence of `.kitkat` in the *current* directory.
    - Commands like `ls-files` or `status` failed when run from a subdirectory (e.g., `cmd/`) because they couldn't find `.kitkat`.
    - **Fix**: The function now recursively checks parent directories until it finds the repository root or hits the system root. If found, it changes the working directory to the repository root so that relative paths (like `.kitkat/index`) resolve correctly.

2.  **Corrupted Index on Init**:
    - `kitkat init` creates an empty `.kitkat/index` file.
    - `LoadIndex` previously attempted to `json.Unmarshal` this empty file, resulting in an "index file corrupted" error/panic immediately after initialization.
    - **Fix**: `LoadIndex` now checks if the file is empty and returns an empty entry list instead of erroring.

## Changes
- `internal/core/helpers.go`: Updated `IsRepoInitialized` to recursively search for `.kitkat`.
- `internal/core/index.go`: Added a check for empty file content in `LoadIndex`.

## Verification
- Verified by creating a reproduction script (`repro.bat`) that initializes a repo, creates a subdirectory, and runs `ls-files`.
- Before fix: `ls-files` failed with "not a kitkat repository".
- After fix: `ls-files` runs successfully (returning empty output for a fresh repo).

Screenshot 2026-01-06 173219

## Related Issues
- Fixing command execution in subdirectories.
- Fixing "index file corrupted" on fresh init.

### CODE REVIEW

**Comment by roshankumar0036singh** [comment]
@Atharv3221 plz review it

File: internal/core/helpers.go [hunk 1]
```diff
@@ -248,55 +248,32 @@ func GetHeadCommit() (models.Commit, error) {
...
-		return err
+		return false
 	}
-	f.Close()
 
-	if err := os.Rename(tmpName, filename); err != nil {
-		return err
-	}
+	for {
+		if _, err := os.Stat(filepath.Join(cwd, ".kitkat")); err == nil {
```
Comment (Atharv3221) [inline internal/core/helpers.go]: use` RepoDir = ".kitkat"` from constants.go

**Comment by roshankumar0036singh** [comment]
@Atharv3221 done
